---

- hosts: jumpbox
  gather_facts: true
  roles:
  - name: osp-facts
# Setup front-end load balancer tier


- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - {name: pre_configuration  }
    - {name: frontend_utils }
    - {name: ha_proxy }

# Setup application servers tier

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: pre_configuration  }
    - {name: tomcat }
    - {name: apache }

# Setup database tier

- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - {name: pre_configuration}
    - {name: postgresql}

