#Gather openstack server instance information for cleaning
- name: OpenStack servers fact gathering
  os_server_facts:
    cloud: ospcloud
  register: openstack_servers
- debug:
    var: openstack_servers
  tags:
    - cleanup

#remove the openstack instances found by the fact gathering
- name: Remove Openstack Server Instances
  os_server:
    cloud: ospcloud
    name: "{{ item.name }}"
    state: absent
    image: rhel-guest
    flavor: m2.small
    delete_fip: true
  with_items: 
  - "{{ openstack_servers.ansible_facts.openstack_servers }}"
  tags:
    - cleanup
